### ISSUE TITLE
Uncaught Exception 

### ISSUE THREAD

**Issue by lgwagner** [agacek/jkind#44]
The IVC engine is crashing with the following error:

jkind.JKindException: Unable to find property event7_false_c4 during reduction
        at jkind.engines.IvcReductionEngine.getInvariantByName(IvcReductionEngine.java:77)
        at jkind.engines.IvcReductionEngine.reduce(IvcReductionEngine.java:65)
        at jkind.engines.IvcReductionEngine.handleMessage(IvcReductionEngine.java:289)
        at jkind.engines.messages.ValidMessage.accept(ValidMessage.java:43)
        at jkind.engines.messages.MessageHandler.handleMessage(MessageHandler.java:31)
        at jkind.engines.messages.MessageHandler.processMessagesAndWaitUntil(MessageHandler.java:39)
        at jkind.engines.IvcReductionEngine.main(IvcReductionEngine.java:59)
        at jkind.engines.Engine.run(Engine.java:35)
        at jkind.engines.SolverBasedEngine.run(SolverBasedEngine.java:37)
        at java.lang.Thread.run(Thread.java:748)

The lustre file to exercise the error is attached as a text file.

[bug.txt](https://github.com/agacek/jkind/files/1744459/bug.txt)

**Comment by lgwagner** [comment]
oops...

jkind -solver z3 -ivc bug.lus
also occurs with
jkind -ivc bug.lus
